// <auto-generated />
using System;
using GameDbManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDbManager.API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250331025703_AddDiscriminatorToItems")]
    partial class AddDiscriminatorToItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameDbManager.API.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Destroyable")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("Dropable")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("Sellable")
                        .HasColumnType("bit");

                    b.Property<bool>("Tradeable")
                        .HasColumnType("bit");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int?>("JewelryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("JewelryId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Stats", (string)null);
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Accessory", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Crystallizable")
                        .HasColumnType("bit");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Items", t =>
                        {
                            t.Property("BodyPart")
                                .HasColumnName("Accessory_BodyPart");

                            t.Property("Crystallizable")
                                .HasColumnName("Accessory_Crystallizable");

                            t.Property("Grade")
                                .HasColumnName("Accessory_Grade");
                        });

                    b.HasDiscriminator().HasValue("Accessory");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Armor", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.Property<string>("ArmorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Crystallizable")
                        .HasColumnType("bit");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Etc", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.Property<bool>("Stackable")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Etc");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Jewelry", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Crystallizable")
                        .HasColumnType("bit");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Items", t =>
                        {
                            t.Property("BodyPart")
                                .HasColumnName("Jewelry_BodyPart");

                            t.Property("Crystallizable")
                                .HasColumnName("Jewelry_Crystallizable");

                            t.Property("Grade")
                                .HasColumnName("Jewelry_Grade");
                        });

                    b.HasDiscriminator().HasValue("Jewelry");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Weapon", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Crystallizable")
                        .HasColumnType("bit");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Items", t =>
                        {
                            t.Property("BodyPart")
                                .HasColumnName("Weapon_BodyPart");

                            t.Property("Crystallizable")
                                .HasColumnName("Weapon_Crystallizable");

                            t.Property("Grade")
                                .HasColumnName("Weapon_Grade");
                        });

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Stat", b =>
                {
                    b.HasOne("GameDbManager.API.Models.Items.Armor", null)
                        .WithMany("Stats")
                        .HasForeignKey("ArmorId");

                    b.HasOne("GameDbManager.API.Models.Items.Jewelry", null)
                        .WithMany("Stats")
                        .HasForeignKey("JewelryId");

                    b.HasOne("GameDbManager.API.Models.Items.Weapon", null)
                        .WithMany("Stats")
                        .HasForeignKey("WeaponId");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Armor", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Jewelry", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Weapon", b =>
                {
                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
