// <auto-generated />
using System;
using GameDbManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDbManager.API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250402224054_MakeItemPropertiesNullable")]
    partial class MakeItemPropertiesNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameDbManager.API.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Crystallizable")
                        .HasColumnType("bit");

                    b.Property<bool>("Destroyable")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("Dropable")
                        .HasColumnType("bit");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("Sellable")
                        .HasColumnType("bit");

                    b.Property<bool>("Tradeable")
                        .HasColumnType("bit");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.ItemSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemSkills");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.ItemStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemStats");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Accessory", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.HasDiscriminator().HasValue("Accessory");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Armor", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.Property<string>("ArmorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Armor");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Etc", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stackable")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Etc");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Jewelry", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.HasDiscriminator().HasValue("Jewelry");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Weapon", b =>
                {
                    b.HasBaseType("GameDbManager.API.Models.Items.Item");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.ItemSkill", b =>
                {
                    b.HasOne("GameDbManager.API.Models.Items.Item", "Item")
                        .WithMany("Skills")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.ItemStat", b =>
                {
                    b.HasOne("GameDbManager.API.Models.Items.Item", "Item")
                        .WithMany("Stats")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GameDbManager.API.Models.Items.Item", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
